# Generated by Django 5.2 on 2025-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='work_units',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Đơn vị công (1 công = 8 giờ)', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mức lương theo ngày công', max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_work_units',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng số công', max_digits=10),
        ),
    ]
